import { createStore } from 'solid-js/store';

const pdfDefaultValues = {
  YourFullName: '',
  PartnerFullName: '',
  Email: '',
  Phone: '',
  BookingRef: '',
  CeremonyType: '',
  CeremonyVenue: '',
  CeremonyDate: '',
  WordingOption: '',
  Rings: '',
  RoomEntrance: '',
  Photographer: '',
  Videographer: '',
  GuestNumber: '',
  Witness1: '',
  Witness2: '',
  YourMum: '',
  YourMumDead: '',
  YourMumJob: '',
  YourMumRetired: '',
  YourDad: '',
  YourDadDead: '',
  YourDadJob: '',
  YourDadRetired: '',
  YourParent1: '',
  YourParent1Dead: '',
  YourParent1Job: '',
  YourParent1Retired: '',
  YourParent2: '',
  YourParent2Dead: '',
  YourParent2Job: '',
  YourParent2Retired: '',
  PartnerParent1: '',
  PartnerParent1Dead: '',
  PartnerParent1Job: '',
  PartnerParent1Retired: '',
  PartnerParent2: '',
  PartnerParent2Dead: '',
  PartnerParent2Job: '',
  PartnerParent2Retired: '',
};

export const [pdfState, setPdfState] = createStore(pdfDefaultValues);
