const formSchemas = [
  {
    YourFirstName: {
      pageUrl: '/your-details',
      label: 'Your first name',
      fieldType: 'text',
      errormessage: 'Please enter your first name',
      required: true,
      autofocus: true,
    },
    YourSurname: {
      pageUrl: '/your-details',
      label: 'Your surname',
      fieldType: 'text',
      errormessage: 'Please enter your surname',
      required: true,
      autofocus: true,
    },
    PartnerFirstName: {
      pageUrl: '/partner',
      label: 'Your partners first name',
      fieldType: 'text',
      errormessage: 'Please enter your partners first name',
      required: true,
      autofocus: true,
    },
    PartnerSurname: {
      pageUrl: '/partner',
      label: 'Your partners surname',
      fieldType: 'text',
      errormessage: 'Please enter your name',
      required: true,
      autofocus: true,
    },
    Email: {
      pageUrl: '/your-details',
      label: 'Your email',
      fieldType: 'text',
      errormessage: 'Enter your full address',
      required: false,
    },
    Phone: {
      pageUrl: '/your-details',
      label: 'Your telephone number',
      fieldType: 'tel',
      errormessage: 'Enter a UK phone number',
      autocomplete: 'tel',
      required: true,
    },
    Date: {
      // calculated field
      pageUrl:'/ceremony',
      label: 'Ceremony date',
      pageUrl: '/ceremony',
      fieldType: 'text',
      errormessage: 'Please enter the day',
      required: true,
    },
  },
];